### ISSUE TITLE
Initial design

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/MiniGH#2]
Let's discuss which activities will we need and draft views for the client.

Edit by @McSinyx: [here is the current design](https://www.figma.com/file/DGwyIIDSE7tm5Lqkk27dkI/miniGH).

**Comment by McSinyx** [comment]
I think [the listing in the sidebar/hamburger menu](https://cli.github.com/manual) would provide *the superset* of what we can do.  Might need to narrow it down a bit to only cover the most essential stuff.

**Comment by Huy-Ngo** [comment]
Here are what I can think of:

- Authentication (create account, log in log out)
- User: view (bio, pinned repos, full repo list, contribution activity)
- Repo: view, create, delete, checkout branches
- Commits: view, comment
- Issues: create, reopen/close/comment
- PRs: view, create, reopen/close/merge/comment, review
- App preference (dark/light mode, font size, ...), accessibility
- Search (user, repo)

**Comment by Huy-Ngo** [comment]
I suppose [https://docs.github.com/en/free-pro-team@latest/rest](GitHub API) allows all of them since these features are supported by the app.

**Comment by PhuongPhg** [comment]
Should we have "filter" for the search?  Like filter the language?

**Comment by PhuongPhg** [comment]
I guess:

- Notifications
- User: avatar: followers, following, organization
- Repo: language, fork,

**Comment by Huy-Ngo** [comment]
Yea, you can star an watch repos too.

**Comment by Huy-Ngo** [comment]
Here are some of my draft. Excuse my lack of professional design tool - these are drawn with [KolourPaint](http://www.kolourpaint.org/)

Login Activity:

![image](https://user-images.githubusercontent.com/19296926/101637768-c2d56080-3a5f-11eb-9bfc-5b0f24edd634.png)

Home Activity (copied and edited from GH):

![image](https://user-images.githubusercontent.com/19296926/101638376-9241f680-3a60-11eb-8105-19a72f5e0364.png)

Drawer/whatever it's called

![image](https://user-images.githubusercontent.com/19296926/101639749-3d06e480-3a62-11eb-9e7a-254cb42d490e.png)

**Comment by Huy-Ngo** [comment]
Well since we kinda finished designing let's close this issue
