### ISSUE TITLE
Make the color and text size more consistent

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/MiniGH#47]
Color: The login activity's color isn't very consistent with the theme in other activities. In addition, set default text color to a darker color (not sure how) rather than the current one.

Size: Currently there are way too many text sizes, some of which are too big to be fit in the screen and some others are too small to be readable. The margins are also not very consistent since many of them are hardcoded.

**Comment by PhuongPhg** [comment]
Some things to the design I think:
- Margin of the box: 16
- Margin left and right of the text in box: 9
- Margin of text to border: 16+9=25
- TextSize: check in Figma (default is 18, some are 20, some are 16)
- Some text color is primary, default is black
- The color of everything is in [Figma](https://www.figma.com/file/DGwyIIDSE7tm5Lqkk27dkI/miniGH?node-id=0%3A1)
- The icon size is 20, except the “add “comment is 24
