### ISSUE TITLE
Add a badge for showing number of repos in ProfileActivity

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/MiniGH#60]
Also, add a pin icon there.

**Comment by Huy-Ngo** [comment]
Helpful resource: https://www.11zon.com/zon/android/how-to-add-badge-counter-in-tablayout-in-android.php

**Comment by McSinyx** [comment]
[**@VanVn**](https://github.com/PhuongPhg), were I to remove the tab layout in GH-66, where should I put the number then?

**Comment by Huy-Ngo** [comment]
GitHub put it to the right but putting it to the left makes sense to me too.

(Yea Ik I wasn't asked)

**Comment by PhuongPhg** [comment]
I still not get the idea where you're gonna put it but i often put badges on the right of the text/title

**Comment by McSinyx** [comment]
I mean there's no longer the text/title anymore :smiley:

**Comment by Huy-Ngo** [comment]
You can add one then?
